### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by amanuel1995** [amanuel1995/MI-449-SS17-741-css-stealing-styles-xedvDK#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://amanuel1995.github.io/MI-449-SS17-741-css-stealing-styles-xedvDK/) and meets the following criteria:

- [x] The page includes the name of your search engine in big letters (you can make it up), with a search `input` below it, then a button below that to run the search (the button doesn't have to do anything for this prototype)
- [x] The font size of the search engine name is at least 70 pixels, so that it's very easy to see
- [x] `span` elements are wrapped around each letter of the name, like this: `<span>G</span><span>o</span><span>o</span><span>g</span><span>l</span><span>e</span>`, so that they can be styled individually with classes
- [x] The on-hover colors from the paragraphs [on this page](http://skillful-clouds.surge.sh/) are used to color individual letters of your name (similar to the letters in Google's logo)
- [x] Inspect the `input` element at the bottom of the [_Prototyping states_ page of the lesson](5) to create an identical-looking search box for your own site (it should even use the same styles on `focus`)
- [x] The styles from the "Create Account" button [on this page](http://plant-servant.surge.sh/) are used for your "Search" button (it should even use the same styles on `hover` and `active`)
- [x] There are no stylelint errors in your CSS (this will also be expected for all future projects)
- [x] All your CSS exists in a `.css` file

**Comment by KatieMFritz** [comment]
Hi Amanuel! 🌴 Great start to this. :smile:

You NAILED IT with the search engine name. Nice job finding those colors, and good move naming your classes by color so they're reusable. 🔥 

The search button also looks really good to me! I'm tired, so hopefully I'm not missing anything. But to my sleep eyes, it looks the same in normal, `hover`, and `focus` states. Nice work. 👍 

### Input element styling
Your `input` is very close to the example, except for in the `focus` state. 

Yours:
![amanuel-input-focus](https://cloud.githubusercontent.com/assets/7085184/23828393/f14ec6b2-069d-11e7-9930-a544c1ba5d1a.png)

Example:
![focus state input](https://cloud.githubusercontent.com/assets/7085184/23828394/fb50078e-069d-11e7-9164-a0162f42d2ba.png)

Let me know if you can't figure out how to make them match! (I'm specifically looking for the outline to be the same color. Sizes and proportions and everything are fine.)

### Input element responsiveness
Check out what happens to your search box when you make the screen narrower. This is because of the `min-width` property you've applied. See if you can find a way to get the styles you want without causing the display to get messy on different size screens! Let me know on Slack if you get stuck. 😄 

### HTML errors
I get one error and one warning when I run your code through the [W3 Validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Famanuel1995.github.io%2FMI-449-SS17-741-css-stealing-styles-xedvDK%2F). You can choose whether to address the warning, but please fix the error. And remember to check future projects with this tool before submitting! 👀

**Comment by KatieMFritz** [comment]
Fantastic! 🔥 💥 🌟 

:shipit:

**Comment by amanuel1995** [comment]
Thank you!!
